name: googleapis_generator_dependency
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  discoveryapis_generator: any
  io: ^1.0.0
  pool: ^1.4.0
  yaml: '>=2.1.0 <4.0.0'

dependency_overrides:
  discoveryapis_generator:
    git:
      path: discoveryapis_generator
      url: https://github.com/google/googleapis.dart.git
      ref: c338236f20bdac0c24c9c5c5c5748b431ee6c3c0
